#include <cstdio>
#include <cstring>
#include <algorithm>
#include <fstream> 
#include <list>
#include <string>
#include <vector>
#include <sstream>
#include <iostream>
#include <cstdlib>
#include <time.h>
#include <cmath>
#include <limits>
#include <stdexcept>
#include <cassert>